###
# Authentication via API Gateway, get access token and assign to `token` variable
###

POST http://localhost:8099/login
Content-Type: application/json

{
  "email": "frank.124@gmail.com",
  "password": "123"
}


> {%
    client.global.set("token", response.body.access_token);
%}
