###
# Create a new cart
###
POST http://localhost:8085/carts
Authorization: Bearer {{token}}

> {%
    client.global.set("cartId", response.body.id);
%}

###
# Get the newly created cart
###
GET http://localhost:8085/carts/{{cartId}}
Authorization: Bearer {{token}}

###
# Add 1st product to cart -> 1st entry
###
POST http://localhost:8085/carts/{{cartId}}/entries?productId={{productId}}&quantity=1
Authorization: Bearer {{token}}

> {%
    client.global.set("entryId", response.body.lineItems[0].id);
%}

###
# Add 2nd product to cart -> 2nd entry
###
POST http://localhost:8085/carts/{{cartId}}/entries?productId={{productId2}}&quantity=1
Authorization: Bearer {{token}}

> {%
    client.global.set("entryId2", response.body.lineItems[0].id);
%}

###
# Update quantity of 1st entry
###
PUT http://localhost:8085/carts/{{cartId}}/entries?cartEntryId={{entryId}}&quantity=3
Authorization: Bearer {{token}}

###
# Delete 2nd entry
###
DELETE http://localhost:8085/carts/{{cartId}}/entries?cartEntryId={{entryId2}}
Authorization: Bearer {{token}}

###
# Select shipping address
###
POST http://localhost:8085/carts/{{cartId}}/shipping-address?shippingAddressId={{shippingAddressId}}
Authorization: Bearer {{token}}

###
# Update credit card
###
POST http://localhost:8085/carts/{{cartId}}/credit-card?creditCardId={{creditCardId}}
Authorization: Bearer {{token}}

###
# Place order
###
POST http://localhost:8085/carts/place-order?cartId={{cartId}}
Authorization: Bearer {{token}}
